### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by LordVenom** [LordVenom/exode_xamarin#4]
Avant sortis beta

- Garder le lecteur en action si on change de page.
- Ajouter des sources
- Gestion favoris, ajout local de video,  gerer en interne pas l'id de tmdb. (Xml ou BDD)
- 2 voir 3 affichage de plus pour les items, en grille, mode 1 par 1 pour l'idée.

Un jour

- 2eme page du detail. (actor) info +
- login et gestion de compte tmdb.

**Comment by Arias800** [comment]
J'ai commencer a faire une roadmp ici : https://github.com/LordVenom/exode_xamarin/projects/1
Pour que ce sois simple a suivre ^^

**Comment by LordVenom** [comment]
ok cool

**Comment by Arias800** [comment]
Faut juste le compléter parce que pour le moment j'ai juste mis des trucs au pif (hors mis le système de favoris que j'ai commencer a faire)  xD

**Comment by LordVenom** [comment]
c'est fait je clos cet issues.
